#  - name: update no servidor
#    apt:
#      update_cache: yes

#  - name: Upgrade no servidor
#    apt:
#      upgrade: dist

#  - name: Instalando Lista de pacotes
#    apt:
#      name: "{{ packages }}"
#    vars:
#      packages:
#      - bind9
#      - dnsutils
#      - python-dbus
#      - python3-dbus

  - name: editar arquivo hosts
    shell: echo "{{ ip_dns }} {{ name_server }} {{ name_server }}.{{ domain }}" > /etc/hosts
  - name: editar arquivo hostname 
    shell: echo "{{ name_server }}" > /etc/hostname
  - name: editar arquivo resolv
    shell: echo "domain {{ domain }}\nsearch {{ domain }}\nnameserver {{ ip_dns }}" > /etc/resolv.conf

  - name: copiando arquivo interfaces
    template:
      src: interfaces
      dest: /etc/network/interfaces
  - name: copiando Zona direta 
    template:
      src: direta
      dest: /etc/bind/db.{{ domain }}
  - name: copiando zona reversa
    template:
      src: reversa
      dest: /etc/bind/db.reverse.{{ domain  }}
  - name: copiando conf.local
    template:
      src: conf-local
      dest: /etc/bind/named.conf.local

  - name: editar forward
    shell: sed -i '/\/\//d' named.conf.options ; sed -i '/};/d' named.conf.options ; echo "forwarders { {{ forward }}; };\n};" >> named.conf.options
    args:
      chdir: /etc/bind


  - name: reinicia bind9
    service:
      name: bind9
      state: reloaded

  - name: reiniciar servidor
    reboot:
