- hosts: webservers
  remote_user: #USER#
  become: yes
  vars:
     porta: 8088
     name_vhost: edson
     diretorio_index: /var/www/edson/
     domain: edson.com
     alias: www.edson.com
     admin: luis
  roles:
    - apache
  
