- hosts: web
  remote_user: root
  gather_facts: no
  vars:
     database: moodle2
     user_database: moodle
     pass_database: moodle
     passwd_new_mysql: root2
     passwd_old_mysql: root
  roles:
    - lamp
    - moodle
