  - name: update no servidor
    apt:
      update_cache: yes

  - name: Upgrade no servidor
    apt:
      upgrade: dist

  - name: Instalando Lista de pacotes
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - php7.0
      - php7.0-ldap
      - php7.0-mysql
      - php7.0-mbstring
      - php7.0-xml
      - php7.0-zip
      - libapache2-mod-php7.0
      - php7.0-common
      - php7.0-xmlrpc 
      - php7.0-soap 
      - php7.0-gd
      - php7.0-cli 
      - php7.0-mcrypt 
      - php7.0-curl
      - apache2
      - mysql-server
      - mysql-client
      - python-mysqldb
      - python-pymysql

  - name: reinicia apache2
    service:
      name: apache2
      state: reloaded

  - name: Configurando senha do Root
    mysql_user: 
      name: root
      password: '{{ passwd_new_mysql }}'
      check_implicit_admin: yes
      login_user: root
      login_password: '{{ passwd_old_mysql }}'
      state: present
