  - name: update no servidor
    apt:
      update_cache: yes

  - name: Upgrade no servidor
    apt:
      upgrade: dist

  - name: Instalando Lista de pacotes
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - php7.3
      - php7.3-ldap
      - php7.3-mysql
      - php7.3-mbstring
      - php7.3-xml
      - php7.3-zip
      - libapache2-mod-php7.3
      - php7.3-common
      - php7.3-xmlrpc 
      - php7.3-soap 
      - php7.3-gd
      - php7.3-cli 
      - php7.3-curl
      - php7.3-intl
      - apache2
      - default-mysql-server
      - default-mysql-client
      - python-pymysql
      - python3-pymysql

  - name: reinicia apache2
    service:
      name: apache2
      state: reloaded

  - name: Configurando senha do Root
    mysql_user: 
      name: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      password: '{{ passwd_new_mysql }}'
      state: present
      login_user: root
