  - name: update no servidor
    apt:
      update_cache: yes

  - name: Upgrade no servidor
    apt:
      upgrade: dist

  - name: Instalando Lista de pacotes
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - php7.2
      - php7.2-ldap
      - php7.2-mysql
      - php7.2-mbstring
      - php7.2-xml
      - php7.2-zip
      - libapache2-mod-php7.2
      - php7.2-common
      - php7.2-xmlrpc 
      - php7.2-soap 
      - php7.2-gd
      - php7.2-cli 
      - php7.2-curl
      - php7.2-intl
      - apache2
      - mysql-server
      - mysql-client
      - python-pymysql
      - python3-pymysql

  - name: reinicia apache2
    service:
      name: apache2
      state: reloaded

  - name: Configurando senha do Root
    mysql_user: 
      name: root
      password: '{{ passwd_new_mysql }}'
      state: present
      login_user: root
      login_password: '{{ passwd_old_mysql }}'
